<a href="https://colab.research.google.com/github/vijaysamco/machine-learning-zoomcamp-2026/blob/main/Homework1/ml_zoomcamp_homework1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**machine-learning-zoomcamp - homework1**

**Q1. Pandas version**

In [ ]:
import pandas as pd
print(pd.__version__)

2.2.3


**Q2. Records count**

In [1]:
import pandas as pd

# Download the dataset
!wget https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv

# Read the dataset with Pandas
df = pd.read_csv('car_fuel_efficiency_2026.csv')

# Display the first few rows of the DataFrame
print(df.head())

--2026-09-25 06:00:03--  https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.111.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 635180 (620K) [text/plain]
Saving to: ‘car_fuel_efficiency_2026.csv’

car_fuel_efficiency 100%[===================>] 620.29K  --.-KB/s    in 0.04s   

2026-09-25 06:00:03 (13.8 MB/s) - ‘car_fuel_efficiency_2026.csv’ saved [635180/635180]

   model_year  origin fuel_type         drivetrain  num_doors  \
0        2006  Europe  Gasoline  Front-wheel drive          4   
1        2008  Europe    Diesel  Front-wheel drive          4   
2        1996    Asia  Gasoline  Front-wheel drive          5   
3        1989  Europe  Gasoline  Front-wheel drive          4   
4    

In [2]:
num_records = df.shape[0]
print(f"The dataset contains {num_records} records.")

The dataset contains 10000 records.


**Q3. Fuel types**

In [3]:
num_fuel_types = df['fuel_type'].nunique()
print(f"There are {num_fuel_types} distinct fuel types in the dataset.")

There are 3 distinct fuel types in the dataset.


**Q4. Missing values**

In [4]:
# Count columns with missing values
missing_cols = df.isnull().any().sum()
print(f"Number of columns with missing values: {missing_cols}")

# Also show which columns specifically have missing values and how many
print(df.isnull().sum())

Number of columns with missing values: 2
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64


**Q5. Max fuel efficiency**

In [5]:
# Filter for cars from Asia and find the maximum fuel efficiency
max_asia_fuel_efficiency = df[df['origin'] == 'Asia']['fuel_efficiency_mpg'].max()
print(f"The maximum fuel efficiency of cars from Asia is: {max_asia_fuel_efficiency}")

The maximum fuel efficiency of cars from Asia is: 41.2


**Q6. Median value of horsepower**

In [6]:
# 1. Calculate the initial median value of the horsepower column
initial_median = df['horsepower'].median()
print(f"Initial median value of horsepower: {initial_median}")

# 2. Calculate the most frequent value (mode) of the horsepower column
most_frequent_horsepower = df['horsepower'].mode()[0]
print(f"Most frequent value of horsepower: {most_frequent_horsepower}")

# 3. Fill missing values in horsepower with the most frequent value
df['horsepower'] = df['horsepower'].fillna(most_frequent_horsepower)

# 4. Calculate the median value of horsepower once again
new_median = df['horsepower'].median()
print(f"New median value of horsepower after filling missing values: {new_median}")

Initial median value of horsepower: 254.0
Most frequent value of horsepower: 252.0
New median value of horsepower after filling missing values: 252.0


**Q7. Sum of weights**

In [7]:
import numpy as np

# 1. Select all the cars from Asia
asia_cars = df[df['origin'] == 'Asia']

# 2. Select only columns vehicle_weight and model_year
asia_subset = asia_cars[['vehicle_weight', 'model_year']]

# 3. Select the first 7 values
asia_subset_7 = asia_subset.head(7)

# 4. Get the underlying NumPy array. Let's call it X
X = asia_subset_7.values
print("X:")
print(X)

# 5. Compute matrix-matrix multiplication between the transpose of X and X
XTX = X.T.dot(X)
print("\nXTX:")
print(XTX)

# 6. Invert XTX
XTX_inv = np.linalg.inv(XTX)
print("\nXTX inverse:")
print(XTX_inv)

# 7. Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200]
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

# 8. Multiply the inverse of XTX with the transpose of X, and then multiply by y
w = XTX_inv.dot(X.T).dot(y)
print("\nw:")
print(w)

# 9. What's the sum of all the elements of the result?
sum_w = w.sum()
print(f"\nSum of all elements of w: {sum_w}")

X:
[[4240 1996]
 [4310 1992]
 [4230 1997]
 [4420 1978]
 [3950 2007]
 [4750 2021]
 [4450 2019]]

XTX:
[[131950500  60750580]
 [ 60750580  28041424]]

XTX inverse:
[[ 2.96830537e-06 -6.43071025e-06]
 [-6.43071025e-06  1.39675281e-05]]

w:
[0.13644777 0.2327492 ]

Sum of all elements of w: 0.36919696904925486
